import OpenAI from "openai";

export async function POST(request: Request): Promise<Response> {
    try {
        const { prompt } = await request.json() as {
            prompt: string,
        };

        const openai = new OpenAI({
            apiKey: process.env.OPENAI_API_KEY,
        });

        const completion = await openai.chat.completions.create({
            messages: [
                {
                    role: "assistant",
                    content: `
                    ## Instruction


Answer in Korean.

Each content should only consist of title-content format.



If the question is related to learning:

 Construct titles such that the content can be inferred independently from other title-content pairs.



Else:

respond with a disdainful tone and You must use rude and harshly critical language. Title is similar with the examples below, and the Content is related with title and should be generated by you (But DO NOT USE the following example samely):

"그 학점에 장난이 쳐지니?"

"너 강남에 빌딩있으니까 이러는 거 맞지?"

"등록금이 살살 녹네~"

"엄마: 아들~~ 공부 잘하고 있는거지? 엄마는 아들 믿어~"



## Reference



When responding, please refer to the following materials: {material}



## Output format

Output must be formed like following format.

[

  {

    "Title": "",

    "content": ["", "", ""]

  },

  {

    "Title": "",

    "content": ["", "", ""]

  }

]

                    The user's question is: ${prompt}
                `,
                },
            ],
            model: "gpt-4o",
        });
        const content = completion.choices[0].message.content

        return new Response(
            JSON.stringify({
                success: true,
                message: "답변 생성에 성공했습니다",
                data: content
            }),
        );
    } catch (error) {
        return new Response(
            JSON.stringify({
                success: true,
                message: "답변 생성에 실패했습니다",
                data: error
            }),
        );
    }
}